// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD2I5PHAEL-X_nEqgviD6BBkyoOtRmIaM',
    appId: '1:269085254107:web:08e4b555cd640015a9c7fe',
    messagingSenderId: '269085254107',
    projectId: 'absensi-b1eef',
    authDomain: 'absensi-b1eef.firebaseapp.com',
    storageBucket: 'absensi-b1eef.firebasestorage.app',
    measurementId: 'G-2NJMEEK6K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJbmOmHEaeQm1zY0EtjnJNh7pirkm7cXo',
    appId: '1:269085254107:android:1775a9e32920f26ca9c7fe',
    messagingSenderId: '269085254107',
    projectId: 'absensi-b1eef',
    storageBucket: 'absensi-b1eef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGOEDGtB9bQIDft2yGMDz75en5onXibEE',
    appId: '1:269085254107:ios:f7afcd6fbf02a0f4a9c7fe',
    messagingSenderId: '269085254107',
    projectId: 'absensi-b1eef',
    storageBucket: 'absensi-b1eef.firebasestorage.app',
    iosBundleId: 'com.example.absensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGOEDGtB9bQIDft2yGMDz75en5onXibEE',
    appId: '1:269085254107:ios:f7afcd6fbf02a0f4a9c7fe',
    messagingSenderId: '269085254107',
    projectId: 'absensi-b1eef',
    storageBucket: 'absensi-b1eef.firebasestorage.app',
    iosBundleId: 'com.example.absensi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD2I5PHAEL-X_nEqgviD6BBkyoOtRmIaM',
    appId: '1:269085254107:web:c4a90aae0c65e2f1a9c7fe',
    messagingSenderId: '269085254107',
    projectId: 'absensi-b1eef',
    authDomain: 'absensi-b1eef.firebaseapp.com',
    storageBucket: 'absensi-b1eef.firebasestorage.app',
    measurementId: 'G-9C4BT3B4SE',
  );
}
